name: simplytranslate
version: 2.0.2
description: Free and unlimited Google translations and TTS. Fast and private.
#author: Marvin Perzi
homepage: https://github.com/Persie0/SimplyTranslate-dart
dependencies:
  http: 1.3.0

dev_dependencies:
  lints: 5.1.1
  test: 1.25.15

environment:
  sdk: ">=2.15.0 <4.0.0"
